config/routes.rb
Rails.application.routes.draw do
  root 'appointments#index'

  devise_for :users
  resources :doctors 
  resources :appointments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :find_doctors
  def index
    @appointments = current_user.appointments
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_user.appointments.new(appt_params)
    if @appointment.save
      redirect_to appointments_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update(appt_params)
      redirect_to appointments_path
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private
    def appt_params
      params.require(:appointment).permit(:name, :doctor_id, :time, :day)
    end

    def set_appointment
      @appointment = current_user.appointments.find(params[:id])
    end

    def find_doctors
      @doctors = Doctor.all
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to doctors_path
    else  
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctors_path
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doc
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :specialty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<div class="container"> 
    <div class="text-center">
        <h1 class="header">Welcome, <%= current_user.full_name %></h1>
        <hr />
    </div>
    <h3>Your Appointments:</h3>
    <% current_user.appointments.each do |appt| %>
        <div class="row border">
            <p class="col-md-4">Reason for visit: <%= appt.name %></p> 
            <p class="col-md-4">Doctor: <%= appt.doctor.name %></p>
            <p class="col-md-4">Time: <%= appt.day %> <%= appt.time.strftime("%l:%M %P") %></p>
            <div class="d-flex justify-content-flex-end">
                <%= button_to 'Cancel Appointment', appointment_path(appt), method: :delete, class: "btn btn-danger" %></li>
            </div>    
        </div>
    <% end %>
    <div class="btn-group" style="margin-top: 10px;">
        <%= button_to 'New Appointment', new_appointment_path, class: "btn btn-primary", method: :get %>
        <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
    </div>
</div>

app/views/appointments/new.html.erb
<%= form_with(model: @appointment, local: true, class: "form-group") do |f| %>
    <div>
        <%= f.label :name, "Enter Your Concern:" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div>
        <%= f.label :doctor, "Pick Your Doctor: " %>
        <%= f.select :doctor_id, @doctors.collect { |d| [d.name, d.id]}, {prompt: "Select Doctor"} , {class: "form-control time-select"}%>
    </div>

    <div>
        <%= f.label :day, "Pick a Day" %>
        <%= f.select :day, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], :prompt => 'Select one'%>
    </div>
    <div>
        <%= f.label :time, "Select a Time: " %>
        <%= f.time_select :time, { minute_step: 15, ampm: true, start_hour: 8, end_hour: 19}, {class: "form-control time-select"} %>
    </div>
    <%= f.submit nil, class: "btn btn-primary" %>

<% end %>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/_form.html.erb
<%= form_with(model: @doctor, local: true, class: "form-group") do |f|%>
    <div class="">
        <%= f.label :name, "Name:"%>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
        <%= f.label :specialty, "Specialty:" %>
        <%= f.text_field :specialty, class: "form-control" %>
    </div>
    <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

    
    

    

app/views/doctors/edit.html.erb
<%= render partial: 'form' %>

app/views/doctors/index.html.erb
<div class="text-center">
    <h1>Our Doctors</h1>
    <hr />
    <%= if current_user.admin? then button_to 'Add a Doctor', new_doctor_path, method: :get, class: "btn btn-primary" end %>
</div>
<div class="card-columns">
    <% @doctors.each do |doc|%>
            <div class="card" style="width: 18rem;">
                <img src="https://robohash.org/<%= doc.specialty %>/?set=set3" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title"><%= doc.name %></h5>
                    <p class="card-text"><%= doc.specialty %></p>
                </div>
                <div class="card-body btn-group">
                        <%= if current_user.admin? then button_to 'Edit Doctor', edit_doctor_path(doc), method: :get, class: "btn btn-primary" end %>
                        <%= if current_user.admin? then button_to 'Remove Doctor', doctor_path(doc), method: :delete, class: "btn btn-danger" end %>
                </div>
            </div>
    
    <% end %>
</div>

app/views/doctors/new.html.erb
<%= render partial: 'form' %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Rails Appointment Manager', root_path, class: "navbar navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Directory of Doctors', doctors_path, class: "nav-item nav-link" %>  
      <%= link_to 'Make an Appointment', new_appointment_path, class: "nav-item nav-link" %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>